### ISSUE TITLE
Add quickstart guide

### ISSUE THREAD

**Issue by anoadragon453** [anoadragon453/nio-template#6]
Just need to finish it up.

**Comment by vlp-git** [comment]
hi @anoadragon453 !

First, thanks for your job !

I juste tried to run it out of the box with a basic config: homeserver + user + passwd and there is an error:

`Traceback (most recent call last):
  File "main.py", line 104, in <module>
    asyncio.get_event_loop().run_until_complete(main())
  File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "main.py", line 34, in main
    config = Config(config_filepath)
  File "/home/vlp/nio-template/config.py", line 45, in __init__
    self.database_filepath = self._get_cfg(["storage", "database_filepath"], required=True)
  File "/home/vlp/nio-template/config.py", line 89, in _get_cfg
    raise ConfigError(f"Config option {'.'.join(path)} is required")
errors.ConfigError: Config option storage.database_filepath is required`

I just modified the config file for the db as below:

`  storage:
  # The path to the database
  database_filepath: "bot.db"
  # The path to a directory for internal bot storage
  # containing encryption keys, sync tokens, etc.
  store_filepath: "/home/vlp/nio-template/store`

I have posted it here because that could help to build the quickstart guide.

Thanks again !

**Comment by anoadragon453** [comment]
Hey @vlp-git, as shown in [sample_config.yaml](https://github.com/anoadragon453/nio-template/blob/master/sample.config.yaml), you'll need to put `database_filepath` (and `store_filepath`) under a `storage` key. Else the code won't be able to find them :)

**Comment by vlp-git** [comment]
Thanks for the quick answer !
What do you mean by "storage key" ! I think that I have missed smth...

**Comment by anoadragon453** [comment]
The options need to be prefaced by `storage:`:

https://github.com/anoadragon453/nio-template/blob/a49c7892515ddbbb8797132188a7608152137154/sample.config.yaml#L22-L27
